### ISSUE TITLE
Java Translation of Kotlin Example

### ISSUE THREAD

**Issue by loren138** [ftomassetti/java-symbol-solver-examples#2]
Hi,

I'm new java Symbol Solver and Kotlin.  I've been trying to translate this example to straight java for ease of understanding for modifications, but I can't quite figure out one line of it.
https://github.com/loren138/code-search-parser/blob/master/src/main/java/me/tomassetti/examples/MethodUsage.java#L35

It looks to me like that chains several kotlin/java-symbol-solver methods together to create the right explorer.  Could you help me translate that line?  I'd be happy to contribute the rest of my translation back such that there is both a java and kotlin translation in the repo if desired.

**Comment by ftomassetti** [comment]
For sure there are automated ways to get Kotlin files from Java files, maybe also the opposite is true.

* `JavaParser.parse(file)` parse the given file and give me a CompilationUnit, i.e., the root of the AST
* Here you can find the definition of the extension method `descendantsOfType` for Node. It is basically a method for Node defined outside the Node class https://github.com/loren138/code-search-parser/blob/d69424779425019a6b884d4f8d1915219703f43a/src/main/kotlin/Utils.kt I use that to find all the instances of the class MethodCallExpr in the AST (MethodCallExpr in Kotlin = MethodCallExpr.class in java)
* I cycle on the list of method calls executing a lambda on each of them. So each method is assigned to the lambda variable `it` and then the lambda code is executed

Is the rest clear?

It is true that using Kotlin is reducing the number of readers who can understand the example.

On the other hand it is so much better than Java...

**Comment by loren138** [comment]
Thanks, I was mostly having trouble translating the descendantsOfType function from Kotlin to something that was workable in Java, but I got it working this morning.  I've added a pull request if you want to have the java edition available. #3
